spring:
  application:
    name: config-server
  profiles:
    active: native,default
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/telemetry/{application}
            - classpath:config/commerce/{application}
            - classpath:config/infra/{application}
    discovery:
      enabled: true
server:
  port: 0

eureka:
  client:
    enable: true
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10