server.port=8080
grpc.server.port: 9090

spring.jackson.time-zone=UTC

logging.level.root=INFO
logging.level.ru.yandex.practicum=DEBUG
logging.level.ru.yandex.practicum.telemetry.collector=DEBUG

# Kafka producer settings
kafka.producer.bootstrap-servers=localhost:9092
kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.producer.value-serializer=ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
kafka.producer.acks=1
kafka.producer.retries=3
kafka.producer.max-in-flight-requests-per-connection=5
kafka.producer.linger-ms=10
kafka.producer.batch-size=16384
