spring.kafka.bootstrap-servers=localhost:9092

aggregator.topic.sensors=telemetry.sensors.v1
aggregator.topic.snapshots=telemetry.snapshots.v1

aggregator.kafka.consumer.bootstrap.servers=${spring.kafka.bootstrap-servers}
aggregator.kafka.consumer.group.id=aggregator.group
aggregator.kafka.consumer.client.id=aggregator-consumer
aggregator.kafka.consumer.enable.auto.commit=false
aggregator.kafka.consumer.auto.offset.reset=earliest
aggregator.kafka.consumer.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer

aggregator.kafka.consumer.value.deserializer=ru.yandex.practicum.kafka.serializer.SensorEventDeserializer
aggregator.kafka.consumer.max.poll.records=100
aggregator.kafka.consumer.fetch.max.bytes=3072000
aggregator.kafka.consumer.max.partition.fetch.bytes=3072000

aggregator.kafka.producer.bootstrap.servers=${spring.kafka.bootstrap-servers}
aggregator.kafka.producer.client.id=aggregator-producer
aggregator.kafka.producer.key.serializer=org.apache.kafka.common.serialization.StringSerializer
aggregator.kafka.producer.value.serializer=ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
aggregator.kafka.producer.acks=all
aggregator.kafka.producer.retries=3
aggregator.kafka.producer.linger.ms=10
aggregator.kafka.producer.batch.size=16384
aggregator.kafka.producer.max.in.flight.requests.per.connection=1
