grpc.client.hub-router.address=static://localhost:59090
grpc.client.hub-router.enableKeepAlive=true
grpc.client.hub-router.keepAliveWithoutCalls=true
grpc.client.hub-router.negotiationType=plaintext

logging.level.ru.yandex.practicum=DEBUG
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.orm.jpa.JpaTransactionManager=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.transaction.interceptor=INFO

analyzer.kafka.bootstrap-servers=localhost:9092
analyzer.kafka.offset-fix-count=10

analyzer.kafka.hubconsumer.properties.bootstrap.servers=${analyzer.kafka.bootstrap-servers}
analyzer.kafka.hubconsumer.properties.enable.auto.commit=false
analyzer.kafka.hubconsumer.properties.client.id=telemetry.analyser.hub.client.v1
analyzer.kafka.hubconsumer.properties.group.id=telemetry.analyser.hub.v1
analyzer.kafka.hubconsumer.properties.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
analyzer.kafka.hubconsumer.properties.value.deserializer=ru.yandex.practicum.kafka.serializer.HubEventDeserializer
analyzer.kafka.hubconsumer.topic=telemetry.hubs.v1
analyzer.kafka.hubconsumer.poll-timeout=200ms

analyzer.kafka.snapshotconsumer.properties.bootstrap.servers=${analyzer.kafka.bootstrap-servers}
analyzer.kafka.snapshotconsumer.properties.enable.auto.commit=false
analyzer.kafka.snapshotconsumer.properties.client.id=telemetry.analyser.snapshot.client.v1
analyzer.kafka.snapshotconsumer.properties.group.id=telemetry.analyser.snapshot.v1
analyzer.kafka.snapshotconsumer.properties.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
analyzer.kafka.snapshotconsumer.properties.value.deserializer=ru.yandex.practicum.kafka.serializer.SensorsSnapshotDeserializer
analyzer.kafka.snapshotconsumer.topic=telemetry.snapshots.v1
analyzer.kafka.snapshotconsumer.poll-timeout=200ms

spring.datasource.url=jdbc:postgresql://localhost:6432/analit
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=analit
spring.datasource.password=analit

spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=none

# --- Analyzer: hub consumer ---
analyzer.streams.hub.topic=telemetry.hubs.v1
analyzer.streams.hub.pollTimeout=PT1S
analyzer.streams.hub.consumer.bootstrap.servers=localhost:9092
analyzer.streams.hub.consumer.group.id=analyzer-hub
analyzer.streams.hub.consumer.enable.auto.commit=false
analyzer.streams.hub.consumer.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
analyzer.streams.hub.consumer.value.deserializer=ru.yandex.practicum.kafka.serializer.HubEventDeserializer

# --- Analyzer: snapshot consumer ---
analyzer.streams.snapshot.topic=telemetry.snapshots.v1
analyzer.streams.snapshot.pollTimeout=PT1S
analyzer.streams.snapshot.consumer.bootstrap.servers=localhost:9092
analyzer.streams.snapshot.consumer.group.id=analyzer-snapshot
analyzer.streams.snapshot.consumer.enable.auto.commit=false
analyzer.streams.snapshot.consumer.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
analyzer.streams.snapshot.consumer.value.deserializer=ru.yandex.practicum.kafka.serializer.SensorsSnapshotDeserializer
