spring:
  datasource:
    url: jdbc:postgresql://localhost:6442/shopping_store_db
    driver-class-name: org.postgresql.Driver
    username: smart_home
    password: smart_home

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

server:
  port: 0
